blog:
  container_name: blog
  image: nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./public:/usr/share/nginx/html:ro
  log_opt:
    max-size: "50m"
