blog:
  container_name: blog
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./public:/usr/share/nginx/html:ro
